# Objetos do Pandas

## Data Frame

Data frames s√£o tabelas que nem de um banco de dados ou arquivo excel ou ate mesmo um dicionario de listas

In [2]:
import pandas as pd

pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})

   a  b
0  1  4
1  2  5
2  3  6

## Series

Series seria algo como um vetor

In [ ]:
pd.Series(["World","Mom"], index=["Hello","world"], name="Test")

Hello    World
world      Mom
Name: Test, dtype: object

## Leitura de arquivos

In [5]:
digimons = pd.read_csv("data/digimons/digimons.csv")
print(f"(i,j): {digimons.shape}")

# save file is
digimons.to_csv("data/digimons/digimons2.csv", index=False)
digimons.head()

(i,j): (249, 13)

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
0,1,Kuramon,Baby,Free,Neutral,2,0,590,77,79,69,68,95
1,2,Pabumon,Baby,Free,Neutral,2,0,950,62,76,76,69,68
2,3,Punimon,Baby,Free,Neutral,2,0,870,50,97,87,50,75
3,4,Botamon,Baby,Free,Neutral,2,0,690,68,77,95,76,61
4,5,Poyomon,Baby,Free,Neutral,2,0,540,98,54,59,95,86

### Para ler uma coluna especifica podemos usar tres formas

In [ ]:
digimons.Digimon
digimons['Digimon']
digimons.iloc[:,1]

0                Kuramon
1                Pabumon
2                Punimon
3                Botamon
4                Poyomon
             ...
244           Valkyrimon
245      ShineGreymon BM
246    MirageGaogamon BM
247           Ravemon BM
248           Rosemon BM
Name: Digimon, Length: 249, dtype: object

#### Para ler multiplas colunas ao mesmo tempo podemos usar o operador de python : ou arrays

In [ ]:
digimons.iloc[[0,1,2],1]
digimons.iloc[0:3,1]

0    Kuramon
1    Pabumon
2    Punimon
Name: Digimon, dtype: object

#### Para ler linhas por nome podemos usar o loc

In [ ]:
digimons.loc[:6,'Digimon']

0    Kuramon
1    Pabumon
2    Punimon
3    Botamon
4    Poyomon
5    Koromon
6    Tanemon
Name: Digimon, dtype: object

### Podemos tambem ler linhas validando uma condi√ß√£o

In [ ]:
digimons.Digimon == 'Kuramon'

0       True
1      False
2      False
3      False
4      False
       ...
244    False
245    False
246    False
247    False
248    False
Name: Digimon, Length: 249, dtype: bool

### Para ler uma celula especifica podemos usar

In [ ]:
digimons['Digimon'][0]

'Kuramon'

### Para ler uma linha especifica podemos usar

In [ ]:
digimons.iloc[0]

Number               1
Digimon        Kuramon
Stage             Baby
Type              Free
Attribute      Neutral
Memory               2
Equip Slots          0
Lv 50 HP           590
Lv50 SP             77
Lv50 Atk            79
Lv50 Def            69
Lv50 Int            68
Lv50 Spd            95
Name: 0, dtype: object

#### Usando condicional para ler linhas

In [ ]:
digimons.loc[(digimons.Digimon == 'MetalGarurumon') | (digimons.Digimon == 'MetalGreymon')]

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
151,152,MetalGreymon,Ultimate,Vaccine,Fire,14,1,1530,84,168,148,80,113
222,223,MetalGarurumon,Mega,Data,Water,18,3,1140,143,154,129,129,178

In [ ]:
digimons.loc[digimons.Stage.isin(['Ultimate','Mega'])]

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
108,109,MegaKabuterimon,Ultimate,Vaccine,Plant,12,2,1430,115,94,163,109,92
109,110,Antylamon,Ultimate,Data,Neutral,12,2,940,123,124,109,114,168
110,111,Andromon,Ultimate,Vaccine,Electric,12,2,1040,94,133,157,133,95
111,112,Meteormon,Ultimate,Data,Earth,12,2,1090,104,123,163,128,89
112,113,Infermon,Ultimate,Free,Dark,14,1,1330,99,198,89,74,153
...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,245,Valkyrimon,Mega,Free,Wind,18,3,1330,139,148,129,129,168
245,246,ShineGreymon BM,Mega,Vaccine,Fire,22,2,1980,114,228,104,84,168
246,247,MirageGaogamon BM,Mega,Data,Light,20,2,1440,124,178,104,158,174
247,248,Ravemon BM,Mega,Vaccine,Wind,20,2,1040,133,149,139,144,213
248,249,Rosemon BM,Mega,Data,Plant,20,2,1480,143,149,139,159,143

In [ ]:
digimons.loc[digimons.Attribute.notnull()]

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
0,1,Kuramon,Baby,Free,Neutral,2,0,590,77,79,69,68,95
1,2,Pabumon,Baby,Free,Neutral,2,0,950,62,76,76,69,68
2,3,Punimon,Baby,Free,Neutral,2,0,870,50,97,87,50,75
3,4,Botamon,Baby,Free,Neutral,2,0,690,68,77,95,76,61
4,5,Poyomon,Baby,Free,Neutral,2,0,540,98,54,59,95,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,245,Valkyrimon,Mega,Free,Wind,18,3,1330,139,148,129,129,168
245,246,ShineGreymon BM,Mega,Vaccine,Fire,22,2,1980,114,228,104,84,168
246,247,MirageGaogamon BM,Mega,Data,Light,20,2,1440,124,178,104,158,174
247,248,Ravemon BM,Mega,Vaccine,Wind,20,2,1040,133,149,139,144,213
248,249,Rosemon BM,Mega,Data,Plant,20,2,1480,143,149,139,159,143

### Mudando o Indice da tabela

In [ ]:
digimons.set_index('Digimon')

,Number,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
Digimon,,,,,,,,,,,,
Kuramon,1,Baby,Free,Neutral,2,0,590,77,79,69,68,95
Pabumon,2,Baby,Free,Neutral,2,0,950,62,76,76,69,68
Punimon,3,Baby,Free,Neutral,2,0,870,50,97,87,50,75
Botamon,4,Baby,Free,Neutral,2,0,690,68,77,95,76,61
Poyomon,5,Baby,Free,Neutral,2,0,540,98,54,59,95,86
...,...,...,...,...,...,...,...,...,...,...,...,...
Valkyrimon,245,Mega,Free,Wind,18,3,1330,139,148,129,129,168
ShineGreymon BM,246,Mega,Vaccine,Fire,22,2,1980,114,228,104,84,168
MirageGaogamon BM,247,Mega,Data,Light,20,2,1440,124,178,104,158,174
Ravemon BM,248,Mega,Vaccine,Wind,20,2,1040,133,149,139,144,213
Rosemon BM,249,Mega,Data,Plant,20,2,1480,143,149,139,159,143

### Alterando dados

In [ ]:
digimons['Novo_index'] = [digimon for digimon in enumerate(digimons['Digimon'])]
digimons['Novo_index']

0                  (0, Kuramon)
1                  (1, Pabumon)
2                  (2, Punimon)
3                  (3, Botamon)
4                  (4, Poyomon)
                 ...
244           (244, Valkyrimon)
245      (245, ShineGreymon BM)
246    (246, MirageGaogamon BM)
247           (247, Ravemon BM)
248           (248, Rosemon BM)
Name: Novo_index, Length: 249, dtype: object

### Fun√ß√£o de Sumario

In [ ]:
digimons['Memory'].describe()

count    249.000000
mean      11.987952
std        6.616501
min        2.000000
25%        6.000000
50%       12.000000
75%       18.000000
max       25.000000
Name: Memory, dtype: float64

In [ ]:
digimons['Attribute'].describe()

count      249
unique       9
top       Dark
freq        37
Name: Attribute, dtype: object

In [ ]:
digimons['Lv 50 HP'].mean()

1210.8835341365461

In [ ]:
digimons['Attribute'].unique()

array(['Neutral', 'Fire', 'Plant', 'Earth', 'Dark', 'Light', 'Water',
       'Wind', 'Electric'], dtype=object)

In [ ]:
digimons['Attribute'].value_counts()

Attribute
Dark        37
Fire        33
Light       29
Neutral     28
Plant       25
Electric    25
Earth       24
Water       24
Wind        24
Name: count, dtype: int64

In [ ]:
# Gera novo DS
digimons['Lv 50 HP'].map(lambda hp: hp + digimons['Lv 50 HP'].max())

0      2670
1      3030
2      2950
3      2770
4      2620
       ...
244    3410
245    4060
246    3520
247    3120
248    3560
Name: Lv 50 HP, Length: 249, dtype: int64

In [ ]:
def balance(digimon):
    digimon['Lv50 Atk'] = digimon['Lv50 Def'] + digimon['Lv50 Spd']
    return digimon

digimons.apply(balance,axis='columns')
# geram novo DS

79
76
97
77
54
109
85
107
108
76
54
60
82
54
82
79
131
124
67
83
82
52
118
123
94
99
133
53
123
93
115
93
53
69
84
86
72
128
66
79
118
103
89
85
94
130
59
61
99
87
59
89
103
92
140
109
89
118
74
109
104
128
155
108
109
108
79
109
99
109
59
143
153
148
153
64
153
68
104
59
131
64
64
143
89
104
143
64
113
148
69
133
108
138
108
84
94
64
138
79
84
113
104
138
103
143
94
133
94
124
133
123
198
148
163
104
69
158
124
137
129
163
173
84
113
119
122
203
150
69
124
128
183
113
161
135
74
139
124
123
104
89
148
64
123
98
158
111
86
158
178
168
173
130
123
128
119
178
69
114
74
163
99
178
183
69
158
188
74
139
198
158
193
193
174
104
203
178
188
84
178
144
124
94
228
94
198
203
193
139
94
149
193
183
89
243
183
149
213
124
159
153
84
193
129
163
94
183
104
74
114
228
89
84
89
198
173
64
208
183
173
134
154
163
99
218
168
99
139
144
144
74
154
208
153
247
89
119
168
158
94
238
188
318
148
228
178
149
149

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd,Novo_index
0,1,Kuramon,Baby,Free,Neutral,2,0,590,77,164,69,68,95,"(0, Kuramon)"
1,2,Pabumon,Baby,Free,Neutral,2,0,950,62,144,76,69,68,"(1, Pabumon)"
2,3,Punimon,Baby,Free,Neutral,2,0,870,50,162,87,50,75,"(2, Punimon)"
3,4,Botamon,Baby,Free,Neutral,2,0,690,68,156,95,76,61,"(3, Botamon)"
4,5,Poyomon,Baby,Free,Neutral,2,0,540,98,145,59,95,86,"(4, Poyomon)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,245,Valkyrimon,Mega,Free,Wind,18,3,1330,139,297,129,129,168,"(244, Valkyrimon)"
245,246,ShineGreymon BM,Mega,Vaccine,Fire,22,2,1980,114,272,104,84,168,"(245, ShineGreymon BM)"
246,247,MirageGaogamon BM,Mega,Data,Light,20,2,1440,124,278,104,158,174,"(246, MirageGaogamon BM)"
247,248,Ravemon BM,Mega,Vaccine,Wind,20,2,1040,133,352,139,144,213,"(247, Ravemon BM)"
248,249,Rosemon BM,Mega,Data,Plant,20,2,1480,143,282,139,159,143,"(248, Rosemon BM)"

In [ ]:
digimons['Digimon'] + " : " + digimons["Attribute"]

0              Kuramon : Neutral
1              Pabumon : Neutral
2              Punimon : Neutral
3              Botamon : Neutral
4              Poyomon : Neutral
                 ...
244            Valkyrimon : Wind
245       ShineGreymon BM : Fire
246    MirageGaogamon BM : Light
247            Ravemon BM : Wind
248           Rosemon BM : Plant
Length: 249, dtype: object

In [ ]:
def isBM(digimon):
    digimon['BM'] = 'BM' in digimon['Digimon']
    return digimon

digimons.apply(isBM,axis='columns')

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd,Novo_index,BM
0,1,Kuramon,Baby,Free,Neutral,2,0,590,77,79,69,68,95,"(0, Kuramon)",False
1,2,Pabumon,Baby,Free,Neutral,2,0,950,62,76,76,69,68,"(1, Pabumon)",False
2,3,Punimon,Baby,Free,Neutral,2,0,870,50,97,87,50,75,"(2, Punimon)",False
3,4,Botamon,Baby,Free,Neutral,2,0,690,68,77,95,76,61,"(3, Botamon)",False
4,5,Poyomon,Baby,Free,Neutral,2,0,540,98,54,59,95,86,"(4, Poyomon)",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,245,Valkyrimon,Mega,Free,Wind,18,3,1330,139,148,129,129,168,"(244, Valkyrimon)",False
245,246,ShineGreymon BM,Mega,Vaccine,Fire,22,2,1980,114,228,104,84,168,"(245, ShineGreymon BM)",True
246,247,MirageGaogamon BM,Mega,Data,Light,20,2,1440,124,178,104,158,174,"(246, MirageGaogamon BM)",True
247,248,Ravemon BM,Mega,Vaccine,Wind,20,2,1040,133,149,139,144,213,"(247, Ravemon BM)",True
248,249,Rosemon BM,Mega,Data,Plant,20,2,1480,143,149,139,159,143,"(248, Rosemon BM)",True

In [12]:
digimons.groupby('Memory')["Memory"].count()

Memory
2      5
3     11
4     19
5     18
6     26
8     29
10     5
12    35
14    18
16     3
18    33
20    17
22    22
25     8
Name: Memory, dtype: int64

In [13]:
digimons.groupby('Memory').agg({'Memory': ['count', 'min', 'max']})

       Memory
        count min max
Memory
2           5   2   2
3          11   3   3
4          19   4   4
5          18   5   5
6          26   6   6
8          29   8   8
10          5  10  10
12         35  12  12
14         18  14  14
16          3  16  16
18         33  18  18
20         17  20  20
22         22  22  22
25          8  25  25

In [18]:
digimons.groupby('Stage').apply(lambda digimon: digimon['Digimon'].iloc[0:3])

Stage
Armor        237          Flamedramon
             238             Magnamon
             239     Rapidmon (Armor)
Baby         0                Kuramon
             1                Pabumon
             2                Punimon
Champion     54            IceDevimon
             55             Aquilamon
             56             Ankylomon
In-Training  5                Koromon
             6                Tanemon
             7               Tsunomon
Mega         166             Alphamon
             167     UlforceVeedramon
             168               Ebemon
Rookie       16                Agumon
             17          Agumon (Blk)
             18          Armadillomon
Ultimate     108      MegaKabuterimon
             109            Antylamon
             110             Andromon
Ultra        232    Imperialdramon PM
             233              Omnimon
             234        Omnimon Zwart
Name: Digimon, dtype: object

In [19]:
digimons.groupby(['Stage','Attribute']).apply(lambda digimon: digimon['Digimon'].iloc[0:3])

Stage  Attribute
Armor  Earth      238             Magnamon
       Fire       237          Flamedramon
       Light      239     Rapidmon (Armor)
Baby   Neutral    0                Kuramon
                  1                Pabumon
                               ...
Ultra  Dark       235         Belphemon RM
                  236           Lucemon SM
       Light      232    Imperialdramon PM
                  233              Omnimon
       Neutral    243             Chaosmon
Name: Digimon, Length: 130, dtype: object

In [21]:
digimons.groupby(['Stage','Type'])['Digimon'].agg([len])

                     len
Stage       Type
Armor       Free       2
            Vaccine    1
Baby        Free       5
Champion    Data      12
            Free       5
            Vaccine   15
            Virus     22
In-Training Free      11
Mega        Data      21
            Free       5
            Vaccine   21
            Virus     27
Rookie      Data      11
            Free       5
            Vaccine   11
            Virus     11
Ultimate    Data      16
            Free       4
            Vaccine   18
            Virus     20
Ultra       Vaccine    4
            Virus      2

In [23]:
digimons.sort_values(by='Lv50 Atk', ascending=False)

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
243,244,Chaosmon,Ultra,Vaccine,Neutral,25,2,1080,129,318,94,89,188
235,236,Belphemon RM,Ultra,Virus,Dark,25,0,1780,84,247,168,109,140
195,196,Diaboromon,Mega,Free,Dark,20,2,1680,114,243,104,79,173
241,242,Beelzemon BM,Mega,Virus,Dark,25,1,1680,114,238,124,104,178
211,212,Beelzemon,Mega,Virus,Dark,22,1,1680,114,228,119,99,168
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,14,Bukamon,In-Training,Free,Water,3,0,830,93,54,74,103,69
10,11,Nyaromon,In-Training,Free,Light,3,0,540,107,54,64,103,94
27,28,Kudamon,Rookie,Vaccine,Light,5,1,590,128,53,74,117,105
32,33,Syakomon,Rookie,Virus,Water,4,1,870,100,53,86,112,78
21,22,Otamamon,Rookie,Virus,Water,4,1,930,105,52,75,113,78

In [25]:
digimons.sort_values(by=['Lv50 Atk','Lv50 Def'], ascending=[False,True])

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
243,244,Chaosmon,Ultra,Vaccine,Neutral,25,2,1080,129,318,94,89,188
235,236,Belphemon RM,Ultra,Virus,Dark,25,0,1780,84,247,168,109,140
195,196,Diaboromon,Mega,Free,Dark,20,2,1680,114,243,104,79,173
241,242,Beelzemon BM,Mega,Virus,Dark,25,1,1680,114,238,124,104,178
184,185,SaberLeomon,Mega,Data,Wind,18,3,1680,99,228,104,84,163
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,11,Nyaromon,In-Training,Free,Light,3,0,540,107,54,64,103,94
13,14,Bukamon,In-Training,Free,Water,3,0,830,93,54,74,103,69
27,28,Kudamon,Rookie,Vaccine,Light,5,1,590,128,53,74,117,105
32,33,Syakomon,Rookie,Virus,Water,4,1,870,100,53,86,112,78
21,22,Otamamon,Rookie,Virus,Water,4,1,930,105,52,75,113,78

In [26]:
digimons.sort_index()

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
0,1,Kuramon,Baby,Free,Neutral,2,0,590,77,79,69,68,95
1,2,Pabumon,Baby,Free,Neutral,2,0,950,62,76,76,69,68
2,3,Punimon,Baby,Free,Neutral,2,0,870,50,97,87,50,75
3,4,Botamon,Baby,Free,Neutral,2,0,690,68,77,95,76,61
4,5,Poyomon,Baby,Free,Neutral,2,0,540,98,54,59,95,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,245,Valkyrimon,Mega,Free,Wind,18,3,1330,139,148,129,129,168
245,246,ShineGreymon BM,Mega,Vaccine,Fire,22,2,1980,114,228,104,84,168
246,247,MirageGaogamon BM,Mega,Data,Light,20,2,1440,124,178,104,158,174
247,248,Ravemon BM,Mega,Vaccine,Wind,20,2,1040,133,149,139,144,213
248,249,Rosemon BM,Mega,Data,Plant,20,2,1480,143,149,139,159,143

In [29]:
digimons.dtypes

Number          int64
Digimon        object
Stage          object
Type           object
Attribute      object
Memory          int64
Equip Slots     int64
Lv 50 HP        int64
Lv50 SP         int64
Lv50 Atk        int64
Lv50 Def        int64
Lv50 Int        int64
Lv50 Spd        int64
dtype: object

In [30]:
digimons['Lv50 Atk'].astype('float64')

0       79.0
1       76.0
2       97.0
3       77.0
4       54.0
       ...
244    148.0
245    228.0
246    178.0
247    149.0
248    149.0
Name: Lv50 Atk, Length: 249, dtype: float64

In [31]:
digimons.index.dtype

dtype('int64')

In [32]:
digimons.rename(columns={'Digimon': 'name'})

,Number,name,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
0,1,Kuramon,Baby,Free,Neutral,2,0,590,77,79,69,68,95
1,2,Pabumon,Baby,Free,Neutral,2,0,950,62,76,76,69,68
2,3,Punimon,Baby,Free,Neutral,2,0,870,50,97,87,50,75
3,4,Botamon,Baby,Free,Neutral,2,0,690,68,77,95,76,61
4,5,Poyomon,Baby,Free,Neutral,2,0,540,98,54,59,95,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,245,Valkyrimon,Mega,Free,Wind,18,3,1330,139,148,129,129,168
245,246,ShineGreymon BM,Mega,Vaccine,Fire,22,2,1980,114,228,104,84,168
246,247,MirageGaogamon BM,Mega,Data,Light,20,2,1440,124,178,104,158,174
247,248,Ravemon BM,Mega,Vaccine,Wind,20,2,1040,133,149,139,144,213
248,249,Rosemon BM,Mega,Data,Plant,20,2,1480,143,149,139,159,143

In [33]:
digimons.rename(index={0: 'firstEntry', 1: 'secondEntry'})

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
firstEntry,1,Kuramon,Baby,Free,Neutral,2,0,590,77,79,69,68,95
secondEntry,2,Pabumon,Baby,Free,Neutral,2,0,950,62,76,76,69,68
2,3,Punimon,Baby,Free,Neutral,2,0,870,50,97,87,50,75
3,4,Botamon,Baby,Free,Neutral,2,0,690,68,77,95,76,61
4,5,Poyomon,Baby,Free,Neutral,2,0,540,98,54,59,95,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,245,Valkyrimon,Mega,Free,Wind,18,3,1330,139,148,129,129,168
245,246,ShineGreymon BM,Mega,Vaccine,Fire,22,2,1980,114,228,104,84,168
246,247,MirageGaogamon BM,Mega,Data,Light,20,2,1440,124,178,104,158,174
247,248,Ravemon BM,Mega,Vaccine,Wind,20,2,1040,133,149,139,144,213
248,249,Rosemon BM,Mega,Data,Plant,20,2,1480,143,149,139,159,143

In [34]:
digimons.rename_axis("id", axis='rows').rename_axis("features", axis='columns') # type: ignore

features,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd
id,,,,,,,,,,,,,
0,1,Kuramon,Baby,Free,Neutral,2,0,590,77,79,69,68,95
1,2,Pabumon,Baby,Free,Neutral,2,0,950,62,76,76,69,68
2,3,Punimon,Baby,Free,Neutral,2,0,870,50,97,87,50,75
3,4,Botamon,Baby,Free,Neutral,2,0,690,68,77,95,76,61
4,5,Poyomon,Baby,Free,Neutral,2,0,540,98,54,59,95,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,245,Valkyrimon,Mega,Free,Wind,18,3,1330,139,148,129,129,168
245,246,ShineGreymon BM,Mega,Vaccine,Fire,22,2,1980,114,228,104,84,168
246,247,MirageGaogamon BM,Mega,Data,Light,20,2,1440,124,178,104,158,174
247,248,Ravemon BM,Mega,Vaccine,Wind,20,2,1040,133,149,139,144,213
248,249,Rosemon BM,Mega,Data,Plant,20,2,1480,143,149,139,159,143

In [36]:
moves = pd.read_csv("data/digimons/moves.csv")
pd.concat([digimons,moves],axis='columns')

,Number,Digimon,Stage,Type,Attribute,Memory,Equip Slots,Lv 50 HP,Lv50 SP,Lv50 Atk,Lv50 Def,Lv50 Int,Lv50 Spd,Move,SP Cost,Type,Power,Attribute,Inheritable,Description
0,1.0,Kuramon,Baby,Free,Neutral,2.0,0.0,590.0,77.0,79.0,69.0,68.0,95.0,Wolkenapalm I,3,Physical,65,Fire,Yes,"Physical attack, 65 Fire damage to one foe. 95..."
1,2.0,Pabumon,Baby,Free,Neutral,2.0,0.0,950.0,62.0,76.0,76.0,69.0,68.0,Wolkenapalm II,6,Physical,85,Fire,Yes,"Physical attack, 85 Fire damage to one foe. 95..."
2,3.0,Punimon,Baby,Free,Neutral,2.0,0.0,870.0,50.0,97.0,87.0,50.0,75.0,Wolkenapalm III,9,Physical,105,Fire,Yes,"Physical attack, 105 Fire damage to one foe. 9..."
3,4.0,Botamon,Baby,Free,Neutral,2.0,0.0,690.0,68.0,77.0,95.0,76.0,61.0,Burst Flame I,3,Magic,55,Fire,Yes,"Magic attack, 55 Fire damage to one foe. 95% a..."
4,5.0,Poyomon,Baby,Free,Neutral,2.0,0.0,540.0,98.0,54.0,59.0,95.0,86.0,Burst Flame II,6,Magic,75,Fire,Yes,"Magic attack, 75 Fire damage to one foe. 95% a..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Garuru Tomahawk,20,Physical,140,Neutral,No,"Physical attack, 140 Neutral damage to one foe..."
383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fist of Athena,50,Physical,0,Fire,No,"DEF-penetrating attack, triple Fire damage to ..."
384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Supreme Cannon,30,Magic,130,Water,No,"Magic attack, 130 Water damage to one foe."
385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dark Prominence,30,Magic,0,Dark,No,INT-penetrating Dark attack to one foe. 50% ch...
386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Plasma Shoot,25,Physical,35,Fire,No,"3 physical attacks, 35 Fire damage to all foes."

In [39]:
left = digimons.set_index(['Memory'])
right = moves.set_index(['SP Cost'])

# left.join(right) not joinable